### ISSUE TITLE
[Recommend] 반응형 레이아웃 완성

### ISSUE THREAD

**Issue by LAPLACE4A** [manga-app-one/samshisaeki#3]
**Location**

samshisaeki/client

**Problem**

Responsive layout support

**Recommendation**

add attribute `flex-wrap: wrap;` at class="sc-jqUVSM fllrPx"
use `@media(min-width: ){}` `@media(max-width: ){}` on Logo

**Comment by LAPLACE4A** [comment]
저거 두개만 해주면 반응형 대충 될거 같은데 시간날때 잠깐 손 좀 봐줘

**Comment by lukekeum** [comment]
@LAPLACE4A 되는대로 한 번 해봤음.
홈페이지에 반영 완료해놨음
